title: Andrew Fisher
email: andrew@andrewfisher.ca
description: >-
  Jesse McGinnis in Waterloo, Canada.
  Solving impactful and complex software problems.

url: "https://andrewfisher.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/"
permalink: pretty

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-environment-variables
  - jekyll-postcss

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
  - scope:
      path: "img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - bin/jekyll
  - bin/serve
